// <auto-generated />
namespace Project.EF.SystemMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FPTsystem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FPTsystem));
        
        string IMigrationMetadata.Id
        {
            get { return "202110141648384_FPTsystem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
